"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import {
  Armchair, ArrowLeft, ArrowRight, Bath, BedDouble, BriefcaseBusiness, Building2,
  Calculator, Check, ChevronDown, CircleHelp, Download, Droplets, Hammer, House,
  LampCeiling, Lightbulb, Paintbrush, PanelsTopLeft, Save, Share2, ShieldCheck,
  Sparkles, Users, Wrench, Zap,
} from "lucide-react";
import { calculateEstimate, formatINR, type EstimatorInputs } from "@/lib/estimator";

const initial: EstimatorInputs = {
  city: "Bengaluru", propertyType: "Apartment", projectType: "renovation", areaSqFt: 1200,
  rooms: 3, requirements: ["Interior design", "Electrical", "Carpentry", "Painting", "Kitchen", "False ceiling", "Lighting"],
  quality: "standard", materialGrade: "standard", timeline: "three_six", budgetMin: 800000,
  budgetMax: 1200000, budgetUnknown: false,
};

const services = [
  ["Interior design", Sparkles], ["Civil work", Building2], ["Electrical", Zap], ["Plumbing", Droplets],
  ["Carpentry", Hammer], ["Painting", Paintbrush], ["Flooring", PanelsTopLeft], ["Kitchen", Wrench],
  ["Bathroom", Bath], ["Furniture", Armchair], ["False ceiling", LampCeiling], ["Lighting", Lightbulb],
] as const;

const money = (value: number) => formatINR(value);

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return <label className="grid min-w-0 gap-2 text-sm font-bold text-[#303238]"><span>{label}</span>{children}</label>;
}

function Select({ value, onChange, children }: { value: string; onChange: (value: string) => void; children: React.ReactNode }) {
  return <span className="relative block"><select value={value} onChange={(event) => onChange(event.target.value)} className="h-11 w-full appearance-none rounded-md border border-[#dededb] bg-white px-3 pr-9 text-sm font-medium outline-none transition focus:border-[#ec4f1c]">{children}</select><ChevronDown size={15} className="pointer-events-none absolute right-3 top-3.5 text-[#737780]" /></span>;
}

function SectionTitle({ number, title, text }: { number: number; title: string; text: string }) {
  return <div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-[#eee8ff] text-lg font-extrabold text-[#654cc8]">{number}</span><div><h2 className="text-base font-extrabold text-[#202126]">{title}</h2><p className="mt-0.5 text-xs leading-5 text-[#747881]">{text}</p></div></div>;
}

export function EstimatorWorkspace() {
  const [inputs, setInputs] = useState(initial);
  const [saved, setSaved] = useState(false);
  const estimate = useMemo(() => calculateEstimate(inputs), [inputs]);
  const set = <K extends keyof EstimatorInputs>(key: K, value: EstimatorInputs[K]) => setInputs((current) => ({ ...current, [key]: value }));
  const toggleService = (name: string) => set("requirements", inputs.requirements.includes(name) ? inputs.requirements.filter((item) => item !== name) : [...inputs.requirements, name]);
  const breakdown = [
    ["Materials", estimate.breakdown.materials, "#f07843"], ["Labour", estimate.breakdown.labour, "#e85d75"],
    ["Professional / Design", estimate.breakdown.professional, "#4d91d7"], ["Execution", estimate.breakdown.execution, "#38a878"],
    ["Other Requirements", estimate.breakdown.other, "#74849c"], ["Contingency", estimate.breakdown.contingency, "#765bc7"],
    ["Taxes", estimate.breakdown.taxes, "#d98a35"],
  ] as const;

  return (
    <div className="min-h-screen bg-[#f8f8f7] text-[#1e2024]">
      <main className="mx-auto max-w-[1600px] px-3 py-5 sm:px-6 sm:py-7">
        <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-bold text-[#e84a18]"><span>Project Planning</span><ChevronDown size={13} className="-rotate-90 text-[#aaa]" /><span className="text-[#282a2f]">Budget Estimator</span></div><h1 className="mt-3 flex items-center gap-2 text-2xl font-extrabold sm:text-[30px]"><Calculator className="text-[#ec4f1c]" size={27} /> Budget Estimator</h1><p className="mt-1 text-sm text-[#656a72]">Get an AI-powered budget range tailored to your requirements. Adjust details to see changes in real time.</p></div><div className="flex gap-2"><Link href="/v2/projects" className="inline-flex h-10 items-center gap-2 rounded-md border border-[#dededb] bg-white px-3 text-xs font-bold"><ArrowLeft size={15} /> Back to projects</Link><button type="button" className="hidden h-10 items-center gap-2 rounded-md border border-[#dededb] bg-white px-3 text-xs font-bold md:inline-flex"><CircleHelp size={15} /> How it works?</button></div></div>

        <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_430px]">
          <div className="grid min-w-0 gap-4">
            <nav className="overflow-x-auto rounded-lg border border-[#e2e2df] bg-white p-3 shadow-sm" aria-label="Estimate progress"><ol className="flex min-w-[710px] items-center justify-between">{["Basic Details", "Requirements", "Quality & Preferences", "Review & Estimate"].map((label, index) => <li key={label} className="flex items-center"><span className={`grid h-9 w-9 place-items-center rounded-full border text-sm font-extrabold ${index === 0 ? "border-[#ec4f1c] bg-[#ec4f1c] text-white" : "border-[#d9d9d6] bg-white text-[#656971]"}`}>{index + 1}</span><span className={`ml-2 whitespace-nowrap text-sm font-bold ${index === 0 ? "text-[#e84a18]" : "text-[#656971]"}`}>{label}</span>{index < 3 && <ArrowRight size={16} className="mx-6 text-[#d4d4d0]" />}</li>)}</ol></nav>

            <section className="rounded-lg border border-[#e2e2df] bg-white p-4 shadow-sm sm:p-6"><SectionTitle number={1} title="Basic Details" text="Tell us about your project" /><div className="mt-6 grid gap-4 md:grid-cols-3"><Field label="Location / City"><Select value={inputs.city} onChange={(value) => set("city", value)}>{["Bengaluru", "Mumbai", "Delhi", "Hyderabad", "Chennai", "Pune", "Kolkata", "Other"].map((city) => <option key={city}>{city}</option>)}</Select></Field><Field label="Property Type"><Select value={inputs.propertyType} onChange={(value) => set("propertyType", value)}>{["Apartment", "Independent house", "Villa", "Office / commercial"].map((type) => <option key={type}>{type}</option>)}</Select></Field><Field label="Project Type"><Select value={inputs.projectType} onChange={(value) => set("projectType", value)}><option value="renovation">Renovation</option><option value="interior">Interior project</option><option value="new_construction">New construction</option><option value="repair">Repair</option></Select></Field><Field label="Built-up Area / Quantity"><div className="flex"><input type="number" min={100} value={inputs.areaSqFt} onChange={(event) => set("areaSqFt", Number(event.target.value))} className="h-11 min-w-0 flex-1 rounded-l-md border border-[#dededb] px-3 text-sm font-semibold outline-none focus:border-[#ec4f1c]" /><span className="grid h-11 place-items-center rounded-r-md border border-l-0 border-[#dededb] bg-[#fafaf9] px-3 text-xs font-bold">sq.ft.</span></div></Field><Field label="Number of Rooms"><Select value={String(inputs.rooms)} onChange={(value) => set("rooms", Number(value))}>{[1,2,3,4,5].map((room) => <option key={room} value={room}>{room === 1 ? "1 Room" : `${room} BHK`}</option>)}</Select></Field><Field label="Timeline"><Select value={inputs.timeline} onChange={(value) => set("timeline", value as EstimatorInputs["timeline"])}><option value="one_three">1 - 3 months</option><option value="three_six">3 - 6 months</option><option value="flexible">Flexible</option><option value="urgent">Urgent</option></Select></Field></div></section>

            <section className="rounded-lg border border-[#e2e2df] bg-white p-4 shadow-sm sm:p-6"><div className="flex items-start justify-between gap-3"><SectionTitle number={2} title="Requirements & Services" text="Select everything that should be included in your project" /><button type="button" onClick={() => set("requirements", inputs.requirements.length === services.length ? [] : services.map(([name]) => name))} className="h-9 shrink-0 rounded-md border border-[#dededb] px-3 text-xs font-bold">Select All</button></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{services.map(([name, Icon]) => { const active = inputs.requirements.includes(name); return <button key={name} type="button" onClick={() => toggleService(name)} aria-pressed={active} className={`relative flex min-h-[62px] items-center gap-3 rounded-md border px-4 text-left text-sm font-bold transition ${active ? "border-[#ed835f] bg-[#fff8f5] text-[#453630] shadow-sm" : "border-[#e0e0dd] bg-white hover:border-[#aaa]"}`}><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full ${active ? "bg-[#fff0e9] text-[#e84a18]" : "bg-[#f5f5f3] text-[#686c74]"}`}><Icon size={16} /></span><span className="min-w-0 leading-5">{name}</span>{active && <span className="absolute right-2 top-2 grid h-4 w-4 place-items-center rounded-sm bg-[#ec4f1c] text-white"><Check size={11} strokeWidth={3} /></span>}</button>})}</div></section>

            <section className="rounded-lg border border-[#e2e2df] bg-white p-4 shadow-sm sm:p-6"><SectionTitle number={3} title="Quality Level & Material Preference" text="Choose quality standards and preferred materials" /><div className="mt-6 grid gap-6 lg:grid-cols-2"><div><h3 className="mb-3 text-sm font-bold">Quality Level</h3><div className="grid grid-cols-2 gap-3">{([['basic','Basic','Essential quality'],['standard','Standard','Good quality'],['premium','Premium','High quality'],['luxury','Luxury','Top quality']] as const).map(([value,label,sub]) => <button key={value} type="button" onClick={() => set("quality", value)} className={`flex min-h-[66px] items-center gap-3 rounded-md border p-3 text-left ${inputs.quality === value ? "border-[#ed835f] bg-[#fff8f5]" : "border-[#e0e0dd]"}`}><span className={`h-4 w-4 shrink-0 rounded-full border-2 ${inputs.quality === value ? "border-[5px] border-[#ec4f1c]" : "border-[#b8bbc0]"}`} /><span><b className="block text-sm">{label}</b><span className="mt-0.5 block text-xs text-[#777b83]">{sub}</span></span></button>)}</div></div><div><h3 className="mb-3 text-sm font-bold">Material Preference</h3><div className="grid grid-cols-2 gap-3">{([['economy','Economy'],['standard','Standard'],['premium','Premium'],['brands','Client Brands']] as const).map(([value,label]) => <button key={value} type="button" onClick={() => set("materialGrade", value)} className={`min-h-[47px] rounded-md border px-3 text-sm font-bold ${inputs.materialGrade === value ? "border-[#ed835f] bg-[#fff8f5] text-[#d74317]" : "border-[#e0e0dd]"}`}>{label}</button>)}</div></div></div></section>

            <section className="rounded-lg border border-[#e2e2df] bg-white p-4 shadow-sm sm:p-6"><SectionTitle number={4} title="Budget Preference" text="Help us understand your expected budget" /><div className="mt-5 flex overflow-x-auto"><button type="button" onClick={() => set("budgetUnknown", false)} className={`h-10 min-w-[170px] rounded-l-md border px-4 text-xs font-bold ${!inputs.budgetUnknown ? "border-[#ec7954] bg-[#fff8f5] text-[#d74317]" : "border-[#dededb]"}`}>Enter Budget Range</button><button type="button" onClick={() => set("budgetUnknown", true)} className={`h-10 min-w-[150px] rounded-r-md border border-l-0 px-4 text-xs font-bold ${inputs.budgetUnknown ? "border-[#ec7954] bg-[#fff8f5] text-[#d74317]" : "border-[#dededb]"}`}>I&apos;m Not Sure</button></div>{!inputs.budgetUnknown && <div className="mt-5 grid gap-4 md:grid-cols-3"><Field label="Minimum Budget"><div className="flex h-11 items-center rounded-md border border-[#dededb] px-3"><span className="mr-2 font-bold">₹</span><input type="number" value={inputs.budgetMin} onChange={(event) => set("budgetMin", Number(event.target.value))} className="min-w-0 flex-1 bg-transparent text-sm font-semibold outline-none" /></div></Field><Field label="Maximum Budget"><div className="flex h-11 items-center rounded-md border border-[#dededb] px-3"><span className="mr-2 font-bold">₹</span><input type="number" value={inputs.budgetMax} onChange={(event) => set("budgetMax", Number(event.target.value))} className="min-w-0 flex-1 bg-transparent text-sm font-semibold outline-none" /></div></Field><Field label="Flexibility"><Select value="moderate" onChange={() => undefined}><option value="moderate">Moderate</option><option value="flexible">Flexible</option><option value="fixed">Fixed</option></Select></Field></div>}<div className="mt-6 grid gap-3 sm:grid-cols-2"><button type="button" onClick={() => setSaved(false)} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md bg-[#ec4f1c] px-4 text-sm font-extrabold text-white shadow-[0_3px_0_#b63713]"><Sparkles size={17} /> Calculate My Budget Range</button><button type="button" onClick={() => setSaved(true)} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-md border border-[#dededb] bg-white px-4 text-sm font-bold"><Save size={16} /> {saved ? "Estimate Saved" : "Save & Continue Later"}</button></div><div className="mt-5 flex items-center gap-2 border-t border-[#ededeb] pt-4 text-xs text-[#747881]"><ShieldCheck size={17} /> Your details are secure and used only for generating accurate estimates.</div></section>
          </div>

          <aside className="grid gap-4 xl:sticky xl:top-5">
            <div className="flex rounded-lg border border-[#e1e1de] bg-white p-2"><button type="button" className="flex h-9 flex-1 items-center justify-center gap-2 text-xs font-bold"><Share2 size={15} /> Share estimate</button><span className="w-px bg-[#e4e4e1]" /><button type="button" className="flex h-9 flex-1 items-center justify-center gap-2 text-xs font-bold"><Download size={15} /> Download PDF</button></div>
            <section className="overflow-hidden rounded-xl bg-[#17153f] p-5 text-white shadow-lg"><div className="flex items-start justify-between gap-3"><p className="text-xs font-bold text-white/75">Your Estimated Budget Range</p><span className="rounded-full bg-[#0b6d59] px-2.5 py-1 text-[10px] font-bold text-[#77efc6]">AI-Powered Estimate</span></div><p className="mt-5 break-words text-2xl font-extrabold tracking-normal sm:text-[30px]">{money(estimate.minimum)} - {money(estimate.maximum)}</p><div className="mt-5 flex items-center gap-3 text-xs"><span className="text-white/70">Confidence Level</span><span className="rounded-full bg-[#0b6d59] px-3 py-1 font-bold">{estimate.confidence}</span></div><p className="mt-2 text-[11px] text-white/55">Based on {inputs.areaSqFt.toLocaleString("en-IN")} sq.ft. and {inputs.requirements.length} requirements</p><div className="mt-5 rounded-lg border border-white/20 bg-white/10 p-3 text-xs leading-5"><span className="inline-flex items-start gap-2"><span className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-[#05a96e]"><Check size={12} /></span>{estimate.budgetMessage}</span></div></section>
            <section className="rounded-lg border border-[#e2e2df] bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-base font-extrabold">Estimated Breakdown</h2><span className="rounded-md bg-[#fff2ec] px-2 py-1 text-[10px] font-bold text-[#e24b1d]">Range</span></div><div className="mt-4 divide-y divide-[#ededeb]">{breakdown.map(([label, values, color]) => <div key={label} className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 py-3 text-xs"><span className="flex min-w-0 items-center gap-2 font-semibold"><span className="h-2 w-2 shrink-0 rounded-full" style={{ backgroundColor: color }} />{label}</span><span className="whitespace-nowrap font-bold">{money(values[0])} - {money(values[1])}</span></div>)}<div className="grid grid-cols-[minmax(0,1fr)_auto] gap-3 pt-4 text-sm font-extrabold"><span>Total Estimate</span><span className="text-right text-[#e84a18]">{money(estimate.minimum)} - {money(estimate.maximum)}</span></div></div></section>
            <section className="rounded-lg border border-[#e2e2df] bg-white p-4 shadow-sm"><h2 className="text-base font-extrabold">What Impacts Your Estimate?</h2><div className="mt-4 grid gap-3">{estimate.drivers.slice(0,4).map((driver, index) => <div key={driver.label} className="flex items-center justify-between gap-3 text-xs"><span className="flex min-w-0 items-center gap-2 text-[#62666e]"><span className={`grid h-5 w-5 shrink-0 place-items-center rounded-full ${index % 2 ? "bg-[#f0eafd] text-[#654cc8]" : "bg-[#fff0e9] text-[#e84a18]"}`}>{index + 1}</span>{driver.label}</span><b className="whitespace-nowrap text-[#e84a18]">+ {money(driver.impact)}</b></div>)}</div></section>
            <section className="rounded-lg border border-[#e2e2df] bg-white p-4 shadow-sm"><h2 className="text-base font-extrabold">Smart Recommendations</h2><div className="mt-4 grid gap-3 text-xs">{[[House,"Switch to economy materials","Save up to ₹5,00,000"],[BedDouble,"Reduce custom furniture scope","Save up to ₹1,80,000"],[BriefcaseBusiness,"Phase non-essential rooms","Spread project cost"]].map(([Icon,title,sub]) => { const ItemIcon = Icon as typeof House; return <div key={String(title)} className="flex items-start gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[#eaf4ff] text-[#397bc3]"><ItemIcon size={15} /></span><span><b className="block leading-5">{String(title)}</b><span className="text-[#747881]">{String(sub)}</span></span></div>})}</div><Link href="/v2/projects" className="mt-5 flex h-11 items-center justify-center gap-2 rounded-md bg-[#ec4f1c] text-sm font-extrabold text-white">Continue to Project Workspace <ArrowRight size={16} /></Link></section>
          </aside>
        </div>
      </main>
      <footer className="mt-4 border-t border-[#e5e5e2] bg-white"><div className="mx-auto grid max-w-[1600px] gap-4 px-6 py-5 text-xs sm:grid-cols-3"><span className="flex items-center gap-2 font-bold"><ShieldCheck className="text-[#3ca678]" size={18} /> Secure estimate</span><span className="flex items-center gap-2 font-bold"><Users className="text-[#4d83c5]" size={18} /> Verified professionals</span><span className="flex items-center gap-2 font-bold"><Wrench className="text-[#765bc7]" size={18} /> Transparent process</span></div></footer>
    </div>
  );
}
