import Link from "next/link";
import { redirect } from "next/navigation";
import { BarChart3, BriefcaseBusiness, FileText, FolderKanban, IndianRupee, Settings, Users } from "lucide-react";
import { createClient } from "@/lib/supabase/server";

export type ProfessionalMode = "overview" | "opportunities" | "proposals" | "projects" | "team" | "documents" | "finance" | "analytics" | "settings";

const modeCopy: Record<ProfessionalMode, [string,string]> = {
  overview:["Business overview","Live activity for this authenticated professional account."],
  opportunities:["Opportunities","Requirements allocated to this professional by Sajivo matching."],
  proposals:["My proposals","Proposals submitted from this account."],
  projects:["Active projects","Projects where this account is the appointed professional."],
  team:["Team & workforce","Verified project and organization team relationships."],
  documents:["Documents","Financial and project documents associated with this account."],
  finance:["Payments & invoices","Recorded payments and financial documents for this account."],
  analytics:["Reports & analytics","Operational totals calculated from live account records."],
  settings:["Business settings","Identity, role and verification information from Supabase."],
};

function Empty({ title }: { title: string }) { return <section className="grid min-h-72 place-items-center border border-dashed border-[#cfd7d2] bg-white p-8 text-center"><div><FolderKanban className="mx-auto text-[#66756e]" size={24}/><h2 className="mt-4 text-sm font-extrabold">No {title.toLowerCase()} yet</h2><p className="mx-auto mt-2 max-w-md text-xs leading-5 text-[#737f79]">No sample records are shown. Eligible activity will appear here after it is created in your Sajivo account.</p></div></section> }
function Status({ value }: { value: string }) { return <span className="rounded-full bg-[#eaf2ed] px-2.5 py-1 text-[9px] font-bold capitalize text-[#476255]">{value.replaceAll("_"," ")}</span> }

export async function LiveProfessionalScreen({ mode }: { mode: ProfessionalMode }) {
  const supabase=await createClient(); if(!supabase)redirect("/login");
  const {data:auth}=await supabase.auth.getUser(); if(!auth.user)redirect("/login"); const id=auth.user.id;
  const [profileResult,opportunitiesResult,proposalsResult,projectsResult,documentsResult,paymentsResult,teamResult]=await Promise.all([
    supabase.from("profiles").select("full_name,business_name,email,primary_role,business_role,verification_status,account_status,account_public_id,city,state").eq("id",id).single(),
    supabase.from("opportunities").select("id,public_id,status,response_deadline,created_at,requirement:requirements!requirement_id(title,project_type,budget,location)").eq("professional_id",id).order("created_at",{ascending:false}),
    supabase.from("proposals").select("id,status,proposed_amount,proposed_amount_min,proposed_amount_max,estimated_timeline,created_at,project:projects!project_id(title,city,state)").eq("professional_id",id).order("created_at",{ascending:false}),
    supabase.from("projects").select("id,title,status,city,state,budget_range,custom_budget,updated_at").eq("selected_professional_id",id).order("updated_at",{ascending:false}),
    supabase.from("financial_documents").select("id,document_number,document_type,total_amount,status,created_at").eq("account_id",id).order("created_at",{ascending:false}),
    supabase.from("payment_records").select("id,public_id,amount,method,status,created_at").eq("account_id",id).order("created_at",{ascending:false}),
    supabase.from("project_team_members").select("id,role,status,project:projects!project_id(title),profile:profiles!profile_id(full_name,email)").eq("profile_id",id).order("created_at",{ascending:false}),
  ]);
  const profile=profileResult.data, opportunities=opportunitiesResult.data??[], proposals=proposalsResult.data??[], projects=projectsResult.data??[], documents=documentsResult.data??[], payments=paymentsResult.data??[], team=teamResult.data??[];
  const [title,description]=modeCopy[mode];
  const Header=()=> <header className="border-b border-[#e1e6e2] pb-6"><h1 className="text-2xl font-extrabold">{title}</h1><p className="mt-2 text-sm text-[#6d7872]">{description}</p></header>;
  if(mode==="overview"||mode==="analytics"){const stats=[[BriefcaseBusiness,"Opportunities",opportunities.length],[FileText,"Proposals",proposals.length],[FolderKanban,"Active projects",projects.length],[IndianRupee,"Payments",payments.length]] as const;return <div className="space-y-6"><Header/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([Icon,label,value])=><section key={label} className="border border-[#dfe5e1] bg-white p-5"><Icon size={18} className="text-[#d65f45]"/><p className="mt-4 text-[10px] font-bold uppercase text-[#7b8580]">{label}</p><p className="mt-1 text-2xl font-extrabold">{value}</p></section>)}</div>{!opportunities.length&&!projects.length?<Empty title="business activity"/>:<section className="border border-[#dfe5e1] bg-white p-5"><h2 className="text-sm font-extrabold">Account status</h2><div className="mt-4 flex flex-wrap gap-2"><Status value={profile?.verification_status||"unverified"}/><Status value={profile?.account_status||"active"}/></div></section>}</div>}
  if(mode==="opportunities")return <div className="space-y-6"><Header/>{opportunities.length?<div className="grid gap-3 lg:grid-cols-2">{opportunities.map(item=>{const req=Array.isArray(item.requirement)?item.requirement[0]:item.requirement;return <article key={item.id} className="border border-[#dfe5e1] bg-white p-5"><div className="flex justify-between gap-3"><div><p className="text-[10px] font-bold text-[#d65f45]">{item.public_id}</p><h2 className="mt-1 font-extrabold">{req?.title||"Opportunity"}</h2><p className="mt-2 text-xs text-[#75807a]">{req?.project_type||"Project requirement"}</p></div><Status value={item.status}/></div></article>})}</div>:<Empty title={title}/>}</div>;
  if(mode==="proposals")return <div className="space-y-6"><Header/>{proposals.length?<div className="divide-y divide-[#e8ece9] border border-[#dfe5e1] bg-white">{proposals.map(item=>{const project=Array.isArray(item.project)?item.project[0]:item.project;return <article key={item.id} className="flex flex-wrap items-center gap-4 p-5 text-xs"><strong className="min-w-0 flex-1">{project?.title||"Project proposal"}</strong><span>{item.proposed_amount?new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(item.proposed_amount)):item.estimated_timeline}</span><Status value={item.status}/></article>})}</div>:<Empty title={title}/>}</div>;
  if(mode==="projects")return <div className="space-y-6"><Header/>{projects.length?<div className="grid gap-3 lg:grid-cols-2">{projects.map(item=><Link href={`/v2/projects/${item.id}`} key={item.id} className="border border-[#dfe5e1] bg-white p-5"><div className="flex justify-between gap-3"><h2 className="font-extrabold">{item.title||"Untitled project"}</h2><Status value={item.status}/></div><p className="mt-3 text-xs text-[#75807a]">{[item.city,item.state].filter(Boolean).join(", ")||"Location pending"}</p></Link>)}</div>:<Empty title={title}/>}</div>;
  if(mode==="documents"||mode==="finance"){const rows=mode==="documents"?documents:payments;return <div className="space-y-6"><Header/>{rows.length?<div className="divide-y divide-[#e8ece9] border border-[#dfe5e1] bg-white">{rows.map((item:any)=><article key={item.id} className="flex flex-wrap items-center gap-4 p-5 text-xs"><strong className="min-w-0 flex-1">{item.document_number||item.public_id}</strong><span>{item.total_amount||item.amount?new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(item.total_amount||item.amount)):""}</span><Status value={item.status}/></article>)}</div>:<Empty title={title}/>}</div>}
  if(mode==="team")return <div className="space-y-6"><Header/>{team.length?<div className="divide-y divide-[#e8ece9] border border-[#dfe5e1] bg-white">{team.map(item=>{const project=Array.isArray(item.project)?item.project[0]:item.project;return <article key={item.id} className="flex items-center gap-4 p-5"><Users size={17}/><div className="flex-1"><strong className="text-sm">{project?.title||"Project team"}</strong><p className="mt-1 text-xs capitalize text-[#75807a]">{item.role}</p></div><Status value={item.status}/></article>})}</div>:<Empty title={title}/>}</div>;
  return <div className="space-y-6"><Header/><section className="grid gap-4 border border-[#dfe5e1] bg-white p-6 sm:grid-cols-2">{[["Business",profile?.business_name||profile?.full_name],["Email",profile?.email],["Role",profile?.business_role||profile?.primary_role],["Verification",profile?.verification_status],["Account ID",profile?.account_public_id],["Location",[profile?.city,profile?.state].filter(Boolean).join(", ")]].map(([label,value])=><div key={label} className="border-b border-[#edf0ee] pb-4"><p className="text-[10px] font-bold uppercase text-[#7b8580]">{label}</p><p className="mt-1 text-sm font-semibold capitalize">{value||"Not provided"}</p></div>)}</section></div>;
}
