import { Building2, Check, Eye, Hammer, Mail, Paintbrush, Phone, ShoppingBag, Store, UserRound, UsersRound } from "lucide-react";
import type { RegistrationData, RegistrationErrors } from "./types";
import { ChoiceCard, Field, Notice, Section } from "./controls";

export function AccountStep({ data, errors, update }: { data: RegistrationData; errors: RegistrationErrors; update: <K extends keyof RegistrationData>(key: K, value: RegistrationData[K]) => void }) {
  const professional = data.businessUse === "professional" || data.businessUse === "both";
  const vendor = data.businessUse === "vendor" || data.businessUse === "both";
  return <div className="p-5 sm:p-6"><Section number={1} title="Choose your account type"><div className="grid gap-3 sm:grid-cols-2"><ChoiceCard active={data.accountType === "client"} title="Client account" description="Post requirements, compare proposals, and manage your project" icon={<UserRound size={22} />} onClick={() => update("accountType", "client")} /><ChoiceCard active={data.accountType === "business"} title="Business account" description="Offer professional services or sell interior products" icon={<Building2 size={22} />} onClick={() => update("accountType", "business")} /></div></Section>
    {data.accountType === "business" && <><Section number={2} title="How will your business use Sajivo?"><div className="grid gap-3 md:grid-cols-3"><ChoiceCard compact active={data.businessUse === "professional"} title="Professional" description="Provide design or project execution services" icon={<UsersRound size={21} />} onClick={() => update("businessUse", "professional")} /><ChoiceCard compact active={data.businessUse === "vendor"} title="Vendor" description="Supply products and materials" icon={<Store size={21} />} onClick={() => update("businessUse", "vendor")} /><ChoiceCard compact active={data.businessUse === "both"} title="Professional & Vendor" description="Offer services and sell products" icon={<Building2 size={21} />} onClick={() => update("businessUse", "both")} /></div></Section>
      {professional && <Section number={3} title="Select your phase-one professional role"><div className="grid gap-3 sm:grid-cols-2"><ChoiceCard active={data.professionalRole === "interior_designer"} title="Interior Designer" description="Create concepts, plans, and design proposals" icon={<Paintbrush size={22} />} onClick={() => update("professionalRole", "interior_designer")} /><ChoiceCard active={data.professionalRole === "contractor"} title="Contractor" description="Quote, coordinate, and execute interior work" icon={<Hammer size={22} />} onClick={() => update("professionalRole", "contractor")} /></div></Section>}
      {vendor && <Section number={professional ? 4 : 3} title="Select your phase-one vendor role"><div className="grid gap-3 sm:grid-cols-3"><ChoiceCard compact active={data.vendorRole === "retailer"} title="Retailer" description="Sell products directly to customers" icon={<ShoppingBag size={20} />} onClick={() => update("vendorRole", "retailer")} /><ChoiceCard compact active={data.vendorRole === "manufacturer"} title="Manufacturer" description="List products you manufacture" icon={<Building2 size={20} />} onClick={() => update("vendorRole", "manufacturer")} /><ChoiceCard compact active={data.vendorRole === "distributor"} title="Distributor" description="Supply brands across service areas" icon={<Store size={20} />} onClick={() => update("vendorRole", "distributor")} /></div></Section>}</>}
    <Section number={data.accountType === "client" ? 2 : (professional && vendor ? 5 : 4)} title="Basic account information"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Full name" placeholder="Enter your full name" value={data.fullName} onChange={(e) => update("fullName", e.target.value)} error={errors.fullName} icon={<UserRound size={15} />} /><Field label="Email address" type="email" placeholder="name@domain.com" value={data.email} onChange={(e) => update("email", e.target.value)} error={errors.email} icon={<Mail size={15} />} /><Field label="Mobile number" type="tel" placeholder="+91 98765 43210" value={data.mobile} onChange={(e) => update("mobile", e.target.value)} error={errors.mobile} icon={<Phone size={15} />} /></div><div className="mt-4"><Field label="Create password" type="password" placeholder="Create a strong password" value={data.password} onChange={(e) => update("password", e.target.value)} error={errors.password} icon={<Eye size={15} />} /></div><div className="mt-2 grid gap-1 text-[10px] text-[#47876a] sm:grid-cols-4">{["8+ characters", "One number", "One uppercase", "One special character"].map((rule) => <span key={rule} className="flex items-center gap-1"><Check size={11} />{rule}</span>)}</div><label className="mt-5 flex cursor-pointer items-start gap-2 text-[11px] leading-5 text-[#555]"><input type="checkbox" checked={data.terms} onChange={(e) => update("terms", e.target.checked)} className="mt-0.5 h-4 w-4 accent-[#e74925]" />I agree to Sajivo&apos;s <span className="font-semibold text-[#d84b2b]">Terms of Service</span> and <span className="font-semibold text-[#d84b2b]">Privacy Policy</span>.</label>{errors.terms && <p className="mt-1 text-[11px] font-medium text-[#c43d3d]">{errors.terms}</p>}{data.accountType === "client" && <div className="mt-5"><Notice tone="green">Client accounts can start projects immediately after email and mobile verification.</Notice></div>}</Section></div>;
}
