import { Building2, Mail, MapPin, Phone, UserRound } from "lucide-react";
import type { RegistrationData, RegistrationErrors } from "./types";
import { Field, Notice, Section, SelectField, TextAreaField, UploadBox } from "./controls";

export function BusinessDetailsStep({ data, errors, update }: { data: RegistrationData; errors: RegistrationErrors; update: <K extends keyof RegistrationData>(key: K, value: RegistrationData[K]) => void }) {
  const f = <K extends keyof RegistrationData>(key: K) => (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => update(key, e.target.value as RegistrationData[K]);
  return <div className="p-5 sm:p-6"><div className="mb-6"><h2 className="text-[18px] font-extrabold">Business details</h2><p className="mt-1 text-[12px] text-[#666]">Tell us about your business. This helps us verify and connect you with the right opportunities.</p></div><Section number={1} title="Business profile"><div className="grid gap-4 sm:grid-cols-2"><Field label="Business / Company name" placeholder="Enter your business name" value={data.companyName} onChange={f("companyName")} error={errors.companyName} icon={<Building2 size={15} />} /><Field label="Trade / Brand name (if different)" placeholder="Enter your brand name" value={data.brandName} onChange={f("brandName")} />
    <SelectField label="Business type" value={data.businessType} onChange={f("businessType")} error={errors.businessType}><option value="">Select business type</option><option>Private Limited Company</option><option>Partnership</option><option>Proprietorship</option><option>LLP</option></SelectField><SelectField label="Business registration type" value={data.registrationType} onChange={f("registrationType")} error={errors.registrationType}><option value="">Select registration type</option><option>Private Limited</option><option>Registered Partnership</option><option>Sole Proprietorship</option><option>Limited Liability Partnership</option></SelectField><Field label="PAN number" placeholder="Enter PAN number" value={data.pan} onChange={f("pan")} error={errors.pan} />
    <div><span className="mb-1.5 block text-[13px] font-semibold">GST registration status</span><div className="grid grid-cols-3 gap-2">{(["registered", "composition", "not_registered"] as const).map((item) => <button key={item} type="button" onClick={() => update("gstStatus", item)} className={`min-h-10 rounded-[5px] border px-2 text-[10px] font-semibold capitalize ${data.gstStatus === item ? "border-[#e74925] bg-[#fff6f2] text-[#cf3f20]" : "border-[#d8d8d8] bg-white"}`}>{item.replace("_", " ")}</button>)}</div></div><Field label="GSTIN (optional)" placeholder="Enter GSTIN number" value={data.gstin} onChange={f("gstin")} error={errors.gstin} /><Field label="Date of establishment" type="date" value={data.established} onChange={f("established")} error={errors.established} /><div><span className="mb-1.5 block text-[13px] font-semibold">Business logo (optional)</span><UploadBox label="Upload logo" description="PNG, JPG or SVG (Max. 2MB)" /></div><div className="grid gap-4"><SelectField label="Business category" value={data.category} onChange={f("category")} error={errors.category}><option value="">Select primary category</option><option>Interior Execution</option><option>Interior Design</option><option>Furniture & Decor</option><option>Building Materials</option></SelectField><SelectField label="Sub category" value={data.subcategory} onChange={f("subcategory")} error={errors.subcategory}><option value="">Select sub category</option><option>Modular Kitchen</option><option>False Ceiling</option><option>Residential Interiors</option><option>Furniture Supply</option></SelectField></div></div></Section>
    <Section number={2} title="Business address"><div className="grid gap-4 sm:grid-cols-2"><Field label="Address line 1" placeholder="House / Building / Street address" value={data.address1} onChange={f("address1")} error={errors.address1} icon={<MapPin size={15} />} /><Field label="Address line 2 (optional)" placeholder="Area / Landmark / Office / Floor" value={data.address2} onChange={f("address2")} /><Field label="City" placeholder="Enter city" value={data.city} onChange={f("city")} error={errors.city} /><SelectField label="State" value={data.state} onChange={f("state")} error={errors.state}><option value="">Select state</option><option>Uttar Pradesh</option><option>Delhi</option><option>Maharashtra</option><option>Karnataka</option></SelectField><Field label="PIN code" inputMode="numeric" placeholder="Enter PIN code" value={data.pincode} onChange={f("pincode")} error={errors.pincode} /><Field label="Service locations" placeholder="Lucknow, Kanpur, Varanasi" value={data.serviceLocations.join(", ")} onChange={(e) => update("serviceLocations", e.target.value.split(",").map((x) => x.trim()).filter(Boolean))} /></div></Section>
    <Section number={3} title="Business contact"><div className="grid gap-4 sm:grid-cols-2"><Field label="Primary mobile number" value={data.mobile} onChange={f("mobile")} error={errors.mobile} icon={<Phone size={15} />} /><Field label="Business email address" type="email" placeholder="Enter business email" value={data.businessEmail} onChange={f("businessEmail")} error={errors.businessEmail} icon={<Mail size={15} />} /><Field label="Alternate mobile (optional)" value={data.alternateMobile} onChange={f("alternateMobile")} /><Field label="Website / Social profile (optional)" placeholder="Enter website or social link" value={data.website} onChange={f("website")} /></div></Section>
    <Section number={4} title="Business bank details (for payouts)"><div className="grid gap-4 sm:grid-cols-2"><Field label="Account holder name" placeholder="Enter name as per bank account" value={data.accountHolder} onChange={f("accountHolder")} error={errors.accountHolder} icon={<UserRound size={15} />} /><Field label="Bank name" placeholder="Enter bank name" value={data.bankName} onChange={f("bankName")} error={errors.bankName} /><Field label="Account number" placeholder="Enter account number" value={data.accountNumber} onChange={f("accountNumber")} error={errors.accountNumber} /><Field label="IFSC code" placeholder="Enter IFSC code" value={data.ifsc} onChange={f("ifsc")} error={errors.ifsc} /></div><div className="mt-4"><Notice tone="peach">Your bank details are securely encrypted and used only for verified payouts.</Notice></div></Section>
    <Section number={5} title="Short business introduction"><div className="grid gap-4 sm:grid-cols-2"><TextAreaField label="About your business" placeholder="Tell us about your business, experience, services and what makes you unique." value={data.about} onChange={f("about")} error={errors.about} maxLength={300} counter={`${data.about.length} / 300`} /><TextAreaField label="Why do you use Sajivo?" placeholder="Share your goals and what you want to achieve on Sajivo." value={data.goals} onChange={f("goals")} maxLength={200} counter={`${data.goals.length} / 200`} /></div></Section></div>;
}
