import type { ReactNode } from "react";
import Link from "next/link";
import { Bot, Check, CircleHelp, LockKeyhole, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { SajivoLogo } from "@/components/brand/SajivoLogo";

const steps = ["Account Type", "Business Details", "Role & Team", "Verification", "Review & Submit"];

function Logo() {
  return <SajivoLogo compact href="/v2" />;
}

function TopSteps({ currentStep, client }: { currentStep: number; client: boolean }) {
  const visible = client ? ["Account Type", "Your Details", "Review & Submit"] : steps;
  const displayStep = client ? (currentStep === 1 ? 1 : currentStep === 5 ? 3 : 2) : currentStep;
  return <ol className="mx-auto mt-7 flex w-full max-w-[840px] items-start" aria-label="Registration progress">{visible.map((label, index) => { const number = index + 1; const done = number < displayStep; const active = number === displayStep; return <li key={label} className="relative flex min-w-0 flex-1 flex-col items-center text-center last:flex-none last:w-[82px]"><span className={`absolute left-[50%] top-3.5 h-px w-full ${number === visible.length ? "hidden" : "block"} ${done ? "bg-[#39b95a]" : "bg-[#d7d7d7]"}`} /><span className={`relative z-10 grid h-7 w-7 place-items-center rounded-full text-[12px] font-bold ${done ? "bg-[#39b95a] text-white" : active ? "bg-[#e74925] text-white" : "bg-[#ededed] text-[#555]"}`}>{done ? <Check size={14} strokeWidth={3} /> : number}</span><span className={`mt-2 max-w-[120px] text-[11px] leading-4 ${active ? "font-extrabold text-[#222]" : "font-medium text-[#555]"}`}>{label}</span></li>; })}</ol>;
}

function WhyRegister() {
  const items = ["Verified professionals only", "Secure & transparent process", "One account, multiple roles", "AI powered matching", "Protected payments", "Built for trust & quality"];
  const icons = [ShieldCheck, LockKeyhole, UsersRound, Sparkles, ShieldCheck, Check];
  return <div className="rounded-[6px] border border-[#e7e7e7] bg-white p-4"><h2 className="text-[13px] font-extrabold">Why register with Sajivo?</h2><ul className="mt-4 space-y-3">{items.map((item, i) => { const Icon = icons[i]; return <li key={item} className="flex items-center gap-2.5 text-[11px] leading-4 text-[#444]"><Icon size={15} className={i % 2 ? "text-[#62a9d7]" : "text-[#58ad8a]"} />{item}</li>; })}</ul></div>;
}

function ProgressCard({ step }: { step: number }) {
  return <div className="rounded-[6px] border border-[#e7e7e7] bg-white p-4"><h2 className="text-[13px] font-extrabold">Progress</h2><p className="mt-2 text-[11px]">You are {step * 20}% done</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#e5e5e5]"><div className="h-full rounded-full bg-[#e74925] transition-all" style={{ width: `${step * 20}%` }} /></div><ol className="mt-4 space-y-3">{steps.map((label, index) => { const number = index + 1; const done = number < step; const active = number === step; return <li key={label} className="flex items-start gap-2.5"><span className={`grid h-4 w-4 shrink-0 place-items-center rounded-full text-[9px] font-bold ${done ? "bg-[#39b95a] text-white" : active ? "bg-[#e74925] text-white" : "bg-[#e6e6e6] text-[#777]"}`}>{done ? <Check size={10} strokeWidth={3} /> : number}</span><span><span className={`block text-[11px] ${active ? "font-extrabold" : "font-semibold"}`}>{label}</span><span className="mt-0.5 block text-[9px] text-[#999]">{done ? "Completed" : active ? "In progress" : "Pending"}</span></span></li>; })}</ol></div>;
}

export function HelpPanel({ step }: { step: number }) {
  const data = step === 5 ? [["Our team will review your information", "Usually within 24 hours"], ["Verification call (if needed)", "We may call to confirm details"], ["Account activation", "Your account is activated after approval"], ["Start receiving opportunities", "Get matched with relevant projects and leads"]] : [["Verification call", "Our team will verify your business and details"], ["Team & document check", "We review your team members and documents"], ["Account activation", "Your account is activated after verification"], ["Start receiving projects", "Get matched with relevant opportunities"]];
  return <aside className="space-y-4"><div className="rounded-[6px] border border-[#e4e4e4] bg-white p-5"><h2 className="text-[14px] font-extrabold">What happens next?</h2><ol className="mt-5 space-y-5">{data.map(([title, text], index) => <li key={title} className="relative flex gap-3"><span className={`grid h-7 w-7 shrink-0 place-items-center rounded-full ${index === 2 ? "bg-[#e9f7ef] text-[#45a873]" : "bg-[#fff4ef] text-[#e56a50]"}`}>{index === 2 ? <ShieldCheck size={16} /> : <UsersRound size={16} />}</span><span><span className="block text-[11px] font-extrabold leading-4">{index + 1}. {title}</span><span className="mt-1 block text-[10px] leading-[17px] text-[#666]">{text}</span></span></li>)}</ol></div><div className="rounded-[6px] border border-[#f0e4de] bg-[#fff9f6] p-4"><h3 className="text-[12px] font-extrabold">Need help?</h3><p className="mt-1 text-[10px] leading-4 text-[#666]">Chat with Angel or call our support team for assistance.</p><Link href="/login?next=%2Fv2%2Fsupport" className="mt-3 flex h-9 w-full items-center justify-center gap-2 rounded-[5px] border border-[#eecfc5] bg-white text-[11px] font-extrabold text-[#333]"><Bot size={16} className="text-[#e74925]" />Talk to Angel</Link></div></aside>;
}

export function RegistrationShell({ step, client, children }: { step: number; client: boolean; children: ReactNode }) {
  return <main data-registration-v2 className="min-h-screen bg-[#fbfbfb] text-[#202020]"><style>{`body:has([data-registration-v2]) > div > header.sticky { display: none; } body:has([data-registration-v2]) nav[aria-label="V2 mobile navigation"], body:has([data-registration-v2]) > aside[aria-label="Appearance and language preferences"], body:has([data-registration-v2]) > button[aria-label="Mute interface sounds"], body:has([data-registration-v2]) > button[aria-label="Enable interface sounds"] { display: none; } body:has([data-registration-v2]) > div > main { padding-bottom: 0; min-height: 100vh; }`}</style><header className="border-b border-[#eeeeee] bg-white"><div className="mx-auto grid max-w-[1440px] grid-cols-[190px_1fr_190px] items-start gap-6 px-5 py-5 max-lg:grid-cols-[1fr_auto] max-sm:px-4"><Logo /><div className="text-center max-lg:order-3 max-lg:col-span-2 max-lg:w-full"><h1 className="text-[30px] font-extrabold leading-tight max-sm:text-[23px]">Create your Sajivo account</h1><p className="mt-1 text-[12px] leading-5 text-[#666]">Start as a client or business. Business users activate a professional or vendor role in phase-one.</p><TopSteps currentStep={step} client={client} /></div><div className="flex items-center justify-end gap-2 pt-1"><span className="text-[10px] text-[#666] max-sm:hidden">Need help?</span><Link href="/login?next=%2Fv2%2Fsupport" title="Talk to Angel" className="flex h-9 items-center gap-2 whitespace-nowrap rounded-[5px] border border-[#efdbd4] bg-white px-3 text-[11px] font-bold"><CircleHelp size={16} className="text-[#e74925]" /><span className="max-sm:hidden">Talk to Angel</span></Link></div></div></header><div className="mx-auto grid max-w-[1440px] grid-cols-[210px_minmax(0,1fr)_250px] items-start gap-5 px-5 py-5 max-xl:grid-cols-[190px_minmax(0,1fr)] max-lg:grid-cols-1 max-sm:px-3"><aside className="space-y-4 max-lg:order-2"><WhyRegister /><div className="rounded-[6px] border border-[#eee2dc] bg-[#fffaf7] p-4"><div className="flex gap-3"><ShieldCheck size={23} className="shrink-0 text-[#e74925]" /><div><h3 className="text-[12px] font-extrabold">Your Safety First</h3><p className="mt-1 text-[10px] leading-[17px] text-[#666]">We verify every business and team to keep our marketplace safe, genuine and reliable.</p></div></div></div>{step > 1 && <ProgressCard step={step} />}</aside><div className="min-w-0 rounded-[7px] border border-[#e7e7e7] bg-white shadow-[0_2px_12px_rgba(0,0,0,.035)]">{children}</div><div className="max-xl:col-start-2 max-xl:row-start-2 max-lg:order-3 max-lg:col-start-auto max-lg:row-start-auto"><HelpPanel step={step} /></div></div></main>;
}
