import { BadgeCheck, CreditCard, FileText, IdCard, Landmark, ShieldCheck } from "lucide-react";
import type { RegistrationData, RegistrationErrors } from "./types";
import { ChoiceCard, Field, Notice, Section, SelectField, UploadBox } from "./controls";

export function VerificationStep({ data, errors, update }: { data: RegistrationData; errors: RegistrationErrors; update: <K extends keyof RegistrationData>(key: K, value: RegistrationData[K]) => void }) {
  return <div className="p-5 sm:p-6"><div className="mb-6"><h2 className="text-[18px] font-extrabold">Verification &amp; authenticity</h2><p className="mt-1 text-[12px] text-[#666]">We verify businesses to ensure trust, safety, and quality on Sajivo.</p></div><Section number={1} title="Identity verification (of primary contact / Team Leader)" description="Upload a government issued identity proof."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Aadhaar Card", "UIDAI issued", "aadhaar", IdCard], ["PAN Card", "Income Tax issued", "pan", CreditCard], ["Passport", "Valid passport", "passport", IdCard], ["Driving License", "Government issued", "license", IdCard]].map(([title, description, value, Icon]) => <ChoiceCard key={String(value)} compact active={data.idType === value} title={String(title)} description={String(description)} icon={<Icon size={20} />} onClick={() => update("idType", String(value))} />)}</div><div className="mt-4 grid gap-4 sm:grid-cols-2"><div><span className="mb-1.5 block text-[12px] font-semibold">Upload front side</span><UploadBox label="Upload front side" /></div><div><span className="mb-1.5 block text-[12px] font-semibold">Upload back side (if applicable)</span><UploadBox label="Upload back side" /></div><Field label="Name as per ID" placeholder="Enter name as per ID" value={data.idName} onChange={(e) => update("idName", e.target.value)} error={errors.idName} /><Field label="ID number" placeholder="Enter ID number" value={data.idNumber} onChange={(e) => update("idNumber", e.target.value)} error={errors.idNumber} /></div></Section>
    <Section number={2} title="Business verification" description="Upload your business registration documents."><div className="grid gap-4 sm:grid-cols-2"><div><span className="mb-1.5 block text-[12px] font-semibold">Business registration certificate</span><UploadBox label="Upload certificate" /></div><div><span className="mb-1.5 block text-[12px] font-semibold">GST certificate (optional)</span><UploadBox label="Upload GST certificate" /></div><Field label="GSTIN (if applicable)" value={data.gstin} onChange={(e) => update("gstin", e.target.value)} /><Field label="Date of registration" type="date" value={data.established} onChange={(e) => update("established", e.target.value)} /></div></Section>
    <Section number={3} title="Business address proof" description="Upload an address proof of your business."><div className="grid gap-4 sm:grid-cols-2"><SelectField label="Select document type" value={data.addressDocument} onChange={(e) => update("addressDocument", e.target.value)} error={errors.addressDocument}><option value="">Select document type</option><option>Utility bill (electricity / water / gas)</option><option>Rental agreement</option><option>Property tax receipt</option></SelectField><div><span className="mb-1.5 block text-[12px] font-semibold">Upload document</span><UploadBox label="Upload document" /></div><Field label="Address on document" placeholder="Enter address as per document" value={data.documentAddress} onChange={(e) => update("documentAddress", e.target.value)} error={errors.documentAddress} /><Field label="Document date" type="date" value={data.documentDate} onChange={(e) => update("documentDate", e.target.value)} error={errors.documentDate} /></div></Section>
    <Section number={4} title="Bank details verification" description="Confirm your bank details for secure payouts."><div className="grid gap-4 sm:grid-cols-3"><Field label="Account holder name" value={data.accountHolder} onChange={(e) => update("accountHolder", e.target.value)} error={errors.accountHolder} /><Field label="Account number" value={data.accountNumber} onChange={(e) => update("accountNumber", e.target.value)} error={errors.accountNumber} /><Field label="IFSC code" value={data.ifsc} onChange={(e) => update("ifsc", e.target.value)} error={errors.ifsc} /></div><div className="mt-4"><Notice tone="peach">All payouts are securely encrypted. We do not display full account numbers.</Notice></div></Section>
    <Section number={5} title="Additional documents (as applicable)" description="Upload any licenses, permits, or supporting documents."><div className="grid gap-4 sm:grid-cols-2"><SelectField label="Document type"><option>Select document type</option><option>Trade license</option><option>Professional certificate</option><option>Other permit</option></SelectField><div><span className="mb-1.5 block text-[12px] font-semibold">Upload document (optional)</span><UploadBox label="Upload document" /></div></div><div className="mt-4"><Notice>You can add more documents after account activation.</Notice></div></Section></div>;
}
